/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package customViews;

import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import metier.Delivery;

/**
 *
 * @author Sylvain
 */
public class DeliveryItem extends javax.swing.JPanel implements ListCellRenderer {

    /**
     * Creates new form livraisonItem
     */
    public DeliveryItem() {
                initComponents();
    }
    public DeliveryItem(Delivery delivery){
                initComponents();
                if(delivery.isValid()){
                     SimpleDateFormat formatDay = new SimpleDateFormat("EEE MMM dd");
                     SimpleDateFormat formatHour = new SimpleDateFormat("HH:mm");

                    this.clientField.setText(delivery.getNomClient());
                    this.contentField.setText(delivery.getContenu());
                    this.dateField.setText(formatDay.format(delivery.getDate()));
                    this.heureField.setText(formatHour.format(delivery.getDate()));
                    this.telNumberField.setText(String.valueOf(delivery.getNumero()));
                    this.livNumberField.setText(String.valueOf(delivery.getId()));
                    clientField.setVisible(true);
                    livNumberField.setVisible(true);
                    
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentLabel = new javax.swing.JLabel();
        clientLabel = new javax.swing.JLabel();
        livNumberLabel = new javax.swing.JLabel();
        telNumberLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        heureLabel = new javax.swing.JLabel();
        contentField = new java.awt.TextField();
        clientField = new java.awt.TextField();
        livNumberField = new java.awt.TextField();
        telNumberField = new java.awt.TextField();
        dateField = new java.awt.TextField();
        heureField = new java.awt.TextField();

        contentLabel.setText("Livraison :");

        clientLabel.setText("Client :");

        livNumberLabel.setText("N° :");

        telNumberLabel.setText("Tel :");

        dateLabel.setText("Date :");

        heureLabel.setText("Heure :");

        contentField.setColumns(40);
        contentField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contentField.setEditable(false);
        contentField.setText("textField1");

        clientField.setColumns(40);
        clientField.setText("textField2");

        livNumberField.setText("textField3");

        telNumberField.setText("textField4");

        dateField.setText("textField5");

        heureField.setText("textField6");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(contentLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(contentField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(clientLabel)
                        .add(30, 30, 30)
                        .add(clientField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(telNumberLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(telNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(livNumberLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(livNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dateLabel)
                    .add(heureLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(heureField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(livNumberLabel)
                                .add(livNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(telNumberLabel)
                                        .add(telNumberField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(heureField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(contentLabel)
                                .add(contentField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(14, 14, 14)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(clientLabel)
                                .add(clientField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(dateLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 22, Short.MAX_VALUE)
                        .add(heureLabel)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField clientField;
    private javax.swing.JLabel clientLabel;
    private java.awt.TextField contentField;
    private javax.swing.JLabel contentLabel;
    private java.awt.TextField dateField;
    private javax.swing.JLabel dateLabel;
    private java.awt.TextField heureField;
    private javax.swing.JLabel heureLabel;
    private java.awt.TextField livNumberField;
    private javax.swing.JLabel livNumberLabel;
    private java.awt.TextField telNumberField;
    private javax.swing.JLabel telNumberLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
       if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        return this;
    }
}
